// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/nbd-com/nbd/v1/nbd.proto

/*
Package v1 is a generated protocol buffer package.

It is generated from these files:

	pkg/nbd-com/nbd/v1/nbd.proto

It has these top-level messages:

	ExportInfoRequest
	ExportInfoResponse
	MapRequest
	MapResponse
	Extent
	ReadRequest
	DataChunk
*/
package v1

import (
	fmt "fmt"

	proto "github.com/golang/protobuf/proto"

	math "math"

	context "golang.org/x/net/context"

	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ExportInfoRequest struct {
	ExportName string `protobuf:"bytes,1,opt,name=exportName" json:"exportName,omitempty"`
}

func (m *ExportInfoRequest) Reset()                    { *m = ExportInfoRequest{} }
func (m *ExportInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*ExportInfoRequest) ProtoMessage()               {}
func (*ExportInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ExportInfoRequest) GetExportName() string {
	if m != nil {
		return m.ExportName
	}
	return ""
}

type ExportInfoResponse struct {
	Size       uint64 `protobuf:"varint,1,opt,name=size" json:"size,omitempty"`
	ExportJson string `protobuf:"bytes,2,opt,name=exportJson" json:"exportJson,omitempty"`
}

func (m *ExportInfoResponse) Reset()                    { *m = ExportInfoResponse{} }
func (m *ExportInfoResponse) String() string            { return proto.CompactTextString(m) }
func (*ExportInfoResponse) ProtoMessage()               {}
func (*ExportInfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ExportInfoResponse) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ExportInfoResponse) GetExportJson() string {
	if m != nil {
		return m.ExportJson
	}
	return ""
}

type MapRequest struct {
	ExportName string `protobuf:"bytes,1,opt,name=exportName" json:"exportName,omitempty"`
	BitmapName string `protobuf:"bytes,2,opt,name=bitmapName" json:"bitmapName,omitempty"`
	Offset     uint64 `protobuf:"varint,3,opt,name=offset" json:"offset,omitempty"`
	Length     uint64 `protobuf:"varint,4,opt,name=length" json:"length,omitempty"`
}

func (m *MapRequest) Reset()                    { *m = MapRequest{} }
func (m *MapRequest) String() string            { return proto.CompactTextString(m) }
func (*MapRequest) ProtoMessage()               {}
func (*MapRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *MapRequest) GetExportName() string {
	if m != nil {
		return m.ExportName
	}
	return ""
}

func (m *MapRequest) GetBitmapName() string {
	if m != nil {
		return m.BitmapName
	}
	return ""
}

func (m *MapRequest) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *MapRequest) GetLength() uint64 {
	if m != nil {
		return m.Length
	}
	return 0
}

type MapResponse struct {
	Extents    []*Extent `protobuf:"bytes,1,rep,name=extents" json:"extents,omitempty"`
	NextOffset uint64    `protobuf:"varint,2,opt,name=next_offset,json=nextOffset" json:"next_offset,omitempty"`
}

func (m *MapResponse) Reset()                    { *m = MapResponse{} }
func (m *MapResponse) String() string            { return proto.CompactTextString(m) }
func (*MapResponse) ProtoMessage()               {}
func (*MapResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *MapResponse) GetExtents() []*Extent {
	if m != nil {
		return m.Extents
	}
	return nil
}

func (m *MapResponse) GetNextOffset() uint64 {
	if m != nil {
		return m.NextOffset
	}
	return 0
}

type Extent struct {
	Offset      uint64 `protobuf:"varint,1,opt,name=offset" json:"offset,omitempty"`
	Length      uint64 `protobuf:"varint,2,opt,name=length" json:"length,omitempty"`
	Type        uint64 `protobuf:"varint,3,opt,name=type" json:"type,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description" json:"description,omitempty"`
}

func (m *Extent) Reset()                    { *m = Extent{} }
func (m *Extent) String() string            { return proto.CompactTextString(m) }
func (*Extent) ProtoMessage()               {}
func (*Extent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Extent) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *Extent) GetLength() uint64 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *Extent) GetType() uint64 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Extent) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type ReadRequest struct {
	ExportName string `protobuf:"bytes,1,opt,name=exportName" json:"exportName,omitempty"`
	Offset     uint64 `protobuf:"varint,2,opt,name=offset" json:"offset,omitempty"`
	Length     uint64 `protobuf:"varint,3,opt,name=length" json:"length,omitempty"`
}

func (m *ReadRequest) Reset()                    { *m = ReadRequest{} }
func (m *ReadRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()               {}
func (*ReadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ReadRequest) GetExportName() string {
	if m != nil {
		return m.ExportName
	}
	return ""
}

func (m *ReadRequest) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ReadRequest) GetLength() uint64 {
	if m != nil {
		return m.Length
	}
	return 0
}

type DataChunk struct {
	Offset uint64 `protobuf:"varint,1,opt,name=offset" json:"offset,omitempty"`
	Data   []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *DataChunk) Reset()                    { *m = DataChunk{} }
func (m *DataChunk) String() string            { return proto.CompactTextString(m) }
func (*DataChunk) ProtoMessage()               {}
func (*DataChunk) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *DataChunk) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *DataChunk) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*ExportInfoRequest)(nil), "kubevirt.nbd.ExportInfoRequest")
	proto.RegisterType((*ExportInfoResponse)(nil), "kubevirt.nbd.ExportInfoResponse")
	proto.RegisterType((*MapRequest)(nil), "kubevirt.nbd.MapRequest")
	proto.RegisterType((*MapResponse)(nil), "kubevirt.nbd.MapResponse")
	proto.RegisterType((*Extent)(nil), "kubevirt.nbd.Extent")
	proto.RegisterType((*ReadRequest)(nil), "kubevirt.nbd.ReadRequest")
	proto.RegisterType((*DataChunk)(nil), "kubevirt.nbd.DataChunk")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for NBD service

type NBDClient interface {
	// Returns metadata (size + JSON info) about the disk export
	GetExportInfo(ctx context.Context, in *ExportInfoRequest, opts ...grpc.CallOption) (*ExportInfoResponse, error)
	// Returns the list of extents for a disk export map
	GetMap(ctx context.Context, in *MapRequest, opts ...grpc.CallOption) (NBD_GetMapClient, error)
	// Reads the disk export and streams back the result
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (NBD_ReadClient, error)
}

type nBDClient struct {
	cc *grpc.ClientConn
}

func NewNBDClient(cc *grpc.ClientConn) NBDClient {
	return &nBDClient{cc}
}

func (c *nBDClient) GetExportInfo(ctx context.Context, in *ExportInfoRequest, opts ...grpc.CallOption) (*ExportInfoResponse, error) {
	out := new(ExportInfoResponse)
	err := grpc.Invoke(ctx, "/kubevirt.nbd.NBD/GetExportInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nBDClient) GetMap(ctx context.Context, in *MapRequest, opts ...grpc.CallOption) (NBD_GetMapClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_NBD_serviceDesc.Streams[0], c.cc, "/kubevirt.nbd.NBD/GetMap", opts...)
	if err != nil {
		return nil, err
	}
	x := &nBDGetMapClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type NBD_GetMapClient interface {
	Recv() (*MapResponse, error)
	grpc.ClientStream
}

type nBDGetMapClient struct {
	grpc.ClientStream
}

func (x *nBDGetMapClient) Recv() (*MapResponse, error) {
	m := new(MapResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *nBDClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (NBD_ReadClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_NBD_serviceDesc.Streams[1], c.cc, "/kubevirt.nbd.NBD/Read", opts...)
	if err != nil {
		return nil, err
	}
	x := &nBDReadClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type NBD_ReadClient interface {
	Recv() (*DataChunk, error)
	grpc.ClientStream
}

type nBDReadClient struct {
	grpc.ClientStream
}

func (x *nBDReadClient) Recv() (*DataChunk, error) {
	m := new(DataChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for NBD service

type NBDServer interface {
	// Returns metadata (size + JSON info) about the disk export
	GetExportInfo(context.Context, *ExportInfoRequest) (*ExportInfoResponse, error)
	// Returns the list of extents for a disk export map
	GetMap(*MapRequest, NBD_GetMapServer) error
	// Reads the disk export and streams back the result
	Read(*ReadRequest, NBD_ReadServer) error
}

func RegisterNBDServer(s *grpc.Server, srv NBDServer) {
	s.RegisterService(&_NBD_serviceDesc, srv)
}

func _NBD_GetExportInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NBDServer).GetExportInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubevirt.nbd.NBD/GetExportInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NBDServer).GetExportInfo(ctx, req.(*ExportInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NBD_GetMap_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MapRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NBDServer).GetMap(m, &nBDGetMapServer{stream})
}

type NBD_GetMapServer interface {
	Send(*MapResponse) error
	grpc.ServerStream
}

type nBDGetMapServer struct {
	grpc.ServerStream
}

func (x *nBDGetMapServer) Send(m *MapResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _NBD_Read_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NBDServer).Read(m, &nBDReadServer{stream})
}

type NBD_ReadServer interface {
	Send(*DataChunk) error
	grpc.ServerStream
}

type nBDReadServer struct {
	grpc.ServerStream
}

func (x *nBDReadServer) Send(m *DataChunk) error {
	return x.ServerStream.SendMsg(m)
}

var _NBD_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kubevirt.nbd.NBD",
	HandlerType: (*NBDServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetExportInfo",
			Handler:    _NBD_GetExportInfo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetMap",
			Handler:       _NBD_GetMap_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Read",
			Handler:       _NBD_Read_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/nbd-com/nbd/v1/nbd.proto",
}

func init() { proto.RegisterFile("pkg/nbd-com/nbd/v1/nbd.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 412 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0x1f, 0x32, 0xca, 0xb8, 0x1c, 0x58, 0x21, 0x30, 0x11, 0xa2, 0x96, 0x4f, 0xbd, 0xe0,
	0xd2, 0xf6, 0xc0, 0x0d, 0x89, 0xd2, 0xaa, 0x80, 0xd4, 0x22, 0x59, 0x9c, 0x90, 0x00, 0xad, 0xe3,
	0x49, 0x62, 0x85, 0xec, 0x2e, 0xde, 0x49, 0x14, 0x10, 0xbf, 0x95, 0xdf, 0x82, 0x76, 0xed, 0xe0,
	0x4d, 0x84, 0xa5, 0x9c, 0x76, 0xf7, 0xcd, 0xcc, 0x9b, 0x37, 0xcf, 0x63, 0x78, 0xa6, 0x16, 0xb3,
	0x53, 0x51, 0x56, 0x2f, 0x26, 0x72, 0x69, 0xce, 0xd3, 0xf5, 0x99, 0x39, 0x72, 0xd5, 0x48, 0x92,
	0xec, 0x68, 0xb1, 0x2a, 0x71, 0x5d, 0x37, 0x94, 0x8b, 0xb2, 0xca, 0x2e, 0xe0, 0xe1, 0xf5, 0x46,
	0xc9, 0x86, 0xde, 0x8b, 0xa9, 0x2c, 0xf0, 0xc7, 0x0a, 0x35, 0xb1, 0xe7, 0x00, 0x68, 0xc1, 0x3b,
	0xbe, 0xc4, 0xc4, 0x4b, 0xbd, 0x93, 0x51, 0xe1, 0x20, 0xd9, 0x3b, 0x60, 0x6e, 0x91, 0x56, 0x52,
	0x68, 0x64, 0x0c, 0x42, 0x5d, 0xff, 0x6a, 0xf3, 0xc3, 0xc2, 0xde, 0x7b, 0xa6, 0x0f, 0x5a, 0x8a,
	0xc4, 0x77, 0x99, 0x0c, 0x92, 0xfd, 0x06, 0xb8, 0xe5, 0xea, 0xc0, 0xbe, 0x26, 0x5e, 0xd6, 0xb4,
	0xe4, 0xca, 0xc6, 0x3b, 0xb6, 0x1e, 0x61, 0x8f, 0x21, 0x92, 0xd3, 0xa9, 0x46, 0x4a, 0x02, 0xab,
	0xa1, 0x7b, 0x19, 0xfc, 0x3b, 0x8a, 0x19, 0xcd, 0x93, 0xb0, 0xc5, 0xdb, 0x57, 0xf6, 0x15, 0x62,
	0xdb, 0xbd, 0x1b, 0x20, 0x87, 0xfb, 0xb8, 0x21, 0x14, 0xa4, 0x13, 0x2f, 0x0d, 0x4e, 0xe2, 0xf3,
	0x47, 0xb9, 0xeb, 0x55, 0x7e, 0x6d, 0x83, 0xc5, 0x36, 0x89, 0x1d, 0x43, 0x2c, 0x70, 0x43, 0xdf,
	0xba, 0x9e, 0xbe, 0xe5, 0x06, 0x03, 0x7d, 0xb4, 0x48, 0x26, 0x20, 0x6a, 0x6b, 0x1c, 0x65, 0xde,
	0x80, 0x32, 0xdf, 0x55, 0x66, 0xbc, 0xa4, 0x9f, 0x0a, 0xbb, 0x39, 0xec, 0x9d, 0xa5, 0x10, 0x57,
	0xa8, 0x27, 0x4d, 0xad, 0xa8, 0x96, 0xc2, 0x8e, 0x32, 0x2a, 0x5c, 0x28, 0xfb, 0x02, 0x71, 0x81,
	0xbc, 0x3a, 0xd4, 0xce, 0x5e, 0x94, 0x3f, 0x20, 0x2a, 0xd8, 0xb1, 0xeb, 0x15, 0x8c, 0xae, 0x38,
	0xf1, 0xb7, 0xf3, 0x95, 0x58, 0x0c, 0x4e, 0xc4, 0x20, 0xac, 0x38, 0x71, 0x4b, 0x79, 0x54, 0xd8,
	0xfb, 0xf9, 0x1f, 0x0f, 0x82, 0xbb, 0xcb, 0x2b, 0xf6, 0x09, 0x1e, 0xdc, 0x20, 0xf5, 0xab, 0xc3,
	0x8e, 0xf7, 0x0d, 0xde, 0xdb, 0xc4, 0x71, 0x3a, 0x9c, 0xd0, 0x7e, 0xb4, 0xec, 0x1e, 0x7b, 0x03,
	0xd1, 0x0d, 0xd2, 0x2d, 0x57, 0x2c, 0xd9, 0xcd, 0xee, 0x37, 0x6b, 0xfc, 0xf4, 0x3f, 0x91, 0x2d,
	0xc1, 0x4b, 0x8f, 0xbd, 0x86, 0xd0, 0x18, 0xc7, 0xf6, 0xd2, 0x1c, 0x33, 0xc7, 0x4f, 0x76, 0x43,
	0xff, 0x8c, 0x30, 0xf5, 0x97, 0xe1, 0x67, 0x7f, 0x7d, 0x56, 0x46, 0xf6, 0x07, 0xbb, 0xf8, 0x1b,
	0x00, 0x00, 0xff, 0xff, 0x54, 0xfd, 0x2f, 0x16, 0x80, 0x03, 0x00, 0x00,
}
