syntax = "proto3";

package kubevirt.nbd;
option go_package = "v1";

service NBD {
    // Returns metadata (size + JSON info) about the disk export
    rpc GetExportInfo(ExportInfoRequest) returns (ExportInfoResponse) {}

    // Returns the list of extents for a disk export map
    rpc GetMap(MapRequest) returns (stream MapResponse) {}

    // Reads the disk export and streams back the result
    rpc Read(ReadRequest) returns (stream DataChunk) {}
}

message ExportInfoRequest {
    string exportName = 1;
}

message ExportInfoResponse {
    uint64 size = 1;
    string exportJson = 2; 
}

message MapRequest {
    string exportName = 1;
    string bitmapName = 2;
    uint64 offset = 3;
    uint64 length = 4;
}

message MapResponse {
    repeated Extent extents = 1;
    uint64 next_offset = 2;
}

message Extent {
    uint64 offset = 1;
    uint64 length = 2;
    uint64 type = 3;
    string description = 4;
}

message ReadRequest {
    string exportName = 1;
    uint64 offset = 2;
    uint64 length = 3;
}

message DataChunk {
    uint64 offset = 1;
    bytes data = 2;
}
