// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/nbd-com/nbd/v1/nbd.proto

/*
Package v1 is a generated protocol buffer package.

It is generated from these files:

	pkg/nbd-com/nbd/v1/nbd.proto

It has these top-level messages:

	ExportInfoRequest
	ExportInfoResponse
	MapRequest
	MapResponse
	DirtyRegion
	ReadRequest
	DataChunk
*/
package v1

import (
	fmt "fmt"

	proto "github.com/golang/protobuf/proto"

	math "math"

	context "golang.org/x/net/context"

	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ExportInfoRequest struct {
	ExportName string `protobuf:"bytes,1,opt,name=exportName" json:"exportName,omitempty"`
}

func (m *ExportInfoRequest) Reset()                    { *m = ExportInfoRequest{} }
func (m *ExportInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*ExportInfoRequest) ProtoMessage()               {}
func (*ExportInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ExportInfoRequest) GetExportName() string {
	if m != nil {
		return m.ExportName
	}
	return ""
}

type ExportInfoResponse struct {
	Size       int64  `protobuf:"varint,1,opt,name=size" json:"size,omitempty"`
	ExportJson []byte `protobuf:"bytes,2,opt,name=exportJson,proto3" json:"exportJson,omitempty"`
}

func (m *ExportInfoResponse) Reset()                    { *m = ExportInfoResponse{} }
func (m *ExportInfoResponse) String() string            { return proto.CompactTextString(m) }
func (*ExportInfoResponse) ProtoMessage()               {}
func (*ExportInfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ExportInfoResponse) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ExportInfoResponse) GetExportJson() []byte {
	if m != nil {
		return m.ExportJson
	}
	return nil
}

type MapRequest struct {
	ExportName string `protobuf:"bytes,1,opt,name=exportName" json:"exportName,omitempty"`
	BitmapName string `protobuf:"bytes,2,opt,name=bitmapName" json:"bitmapName,omitempty"`
}

func (m *MapRequest) Reset()                    { *m = MapRequest{} }
func (m *MapRequest) String() string            { return proto.CompactTextString(m) }
func (*MapRequest) ProtoMessage()               {}
func (*MapRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *MapRequest) GetExportName() string {
	if m != nil {
		return m.ExportName
	}
	return ""
}

func (m *MapRequest) GetBitmapName() string {
	if m != nil {
		return m.BitmapName
	}
	return ""
}

type MapResponse struct {
	Regions []*DirtyRegion `protobuf:"bytes,1,rep,name=regions" json:"regions,omitempty"`
}

func (m *MapResponse) Reset()                    { *m = MapResponse{} }
func (m *MapResponse) String() string            { return proto.CompactTextString(m) }
func (*MapResponse) ProtoMessage()               {}
func (*MapResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *MapResponse) GetRegions() []*DirtyRegion {
	if m != nil {
		return m.Regions
	}
	return nil
}

type DirtyRegion struct {
	Offset int64 `protobuf:"varint,1,opt,name=offset" json:"offset,omitempty"`
	Length int64 `protobuf:"varint,2,opt,name=length" json:"length,omitempty"`
}

func (m *DirtyRegion) Reset()                    { *m = DirtyRegion{} }
func (m *DirtyRegion) String() string            { return proto.CompactTextString(m) }
func (*DirtyRegion) ProtoMessage()               {}
func (*DirtyRegion) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *DirtyRegion) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *DirtyRegion) GetLength() int64 {
	if m != nil {
		return m.Length
	}
	return 0
}

type ReadRequest struct {
	ExportName string `protobuf:"bytes,1,opt,name=exportName" json:"exportName,omitempty"`
	Offset     int64  `protobuf:"varint,2,opt,name=offset" json:"offset,omitempty"`
	Length     int64  `protobuf:"varint,3,opt,name=length" json:"length,omitempty"`
}

func (m *ReadRequest) Reset()                    { *m = ReadRequest{} }
func (m *ReadRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()               {}
func (*ReadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ReadRequest) GetExportName() string {
	if m != nil {
		return m.ExportName
	}
	return ""
}

func (m *ReadRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ReadRequest) GetLength() int64 {
	if m != nil {
		return m.Length
	}
	return 0
}

type DataChunk struct {
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *DataChunk) Reset()                    { *m = DataChunk{} }
func (m *DataChunk) String() string            { return proto.CompactTextString(m) }
func (*DataChunk) ProtoMessage()               {}
func (*DataChunk) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *DataChunk) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*ExportInfoRequest)(nil), "kubevirt.nbd.ExportInfoRequest")
	proto.RegisterType((*ExportInfoResponse)(nil), "kubevirt.nbd.ExportInfoResponse")
	proto.RegisterType((*MapRequest)(nil), "kubevirt.nbd.MapRequest")
	proto.RegisterType((*MapResponse)(nil), "kubevirt.nbd.MapResponse")
	proto.RegisterType((*DirtyRegion)(nil), "kubevirt.nbd.DirtyRegion")
	proto.RegisterType((*ReadRequest)(nil), "kubevirt.nbd.ReadRequest")
	proto.RegisterType((*DataChunk)(nil), "kubevirt.nbd.DataChunk")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for NBD service

type NBDClient interface {
	// Returns metadata (size + JSON info) about the disk export
	GetExportInfo(ctx context.Context, in *ExportInfoRequest, opts ...grpc.CallOption) (*ExportInfoResponse, error)
	// Returns the list of dirty regions for incremental backup
	GetDirtyBitmap(ctx context.Context, in *MapRequest, opts ...grpc.CallOption) (*MapResponse, error)
	// High-performance data path for reading specific dirty regions
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (NBD_ReadClient, error)
}

type nBDClient struct {
	cc *grpc.ClientConn
}

func NewNBDClient(cc *grpc.ClientConn) NBDClient {
	return &nBDClient{cc}
}

func (c *nBDClient) GetExportInfo(ctx context.Context, in *ExportInfoRequest, opts ...grpc.CallOption) (*ExportInfoResponse, error) {
	out := new(ExportInfoResponse)
	err := grpc.Invoke(ctx, "/kubevirt.nbd.NBD/GetExportInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nBDClient) GetDirtyBitmap(ctx context.Context, in *MapRequest, opts ...grpc.CallOption) (*MapResponse, error) {
	out := new(MapResponse)
	err := grpc.Invoke(ctx, "/kubevirt.nbd.NBD/GetDirtyBitmap", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nBDClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (NBD_ReadClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_NBD_serviceDesc.Streams[0], c.cc, "/kubevirt.nbd.NBD/Read", opts...)
	if err != nil {
		return nil, err
	}
	x := &nBDReadClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type NBD_ReadClient interface {
	Recv() (*DataChunk, error)
	grpc.ClientStream
}

type nBDReadClient struct {
	grpc.ClientStream
}

func (x *nBDReadClient) Recv() (*DataChunk, error) {
	m := new(DataChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for NBD service

type NBDServer interface {
	// Returns metadata (size + JSON info) about the disk export
	GetExportInfo(context.Context, *ExportInfoRequest) (*ExportInfoResponse, error)
	// Returns the list of dirty regions for incremental backup
	GetDirtyBitmap(context.Context, *MapRequest) (*MapResponse, error)
	// High-performance data path for reading specific dirty regions
	Read(*ReadRequest, NBD_ReadServer) error
}

func RegisterNBDServer(s *grpc.Server, srv NBDServer) {
	s.RegisterService(&_NBD_serviceDesc, srv)
}

func _NBD_GetExportInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NBDServer).GetExportInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubevirt.nbd.NBD/GetExportInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NBDServer).GetExportInfo(ctx, req.(*ExportInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NBD_GetDirtyBitmap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NBDServer).GetDirtyBitmap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubevirt.nbd.NBD/GetDirtyBitmap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NBDServer).GetDirtyBitmap(ctx, req.(*MapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NBD_Read_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NBDServer).Read(m, &nBDReadServer{stream})
}

type NBD_ReadServer interface {
	Send(*DataChunk) error
	grpc.ServerStream
}

type nBDReadServer struct {
	grpc.ServerStream
}

func (x *nBDReadServer) Send(m *DataChunk) error {
	return x.ServerStream.SendMsg(m)
}

var _NBD_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kubevirt.nbd.NBD",
	HandlerType: (*NBDServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetExportInfo",
			Handler:    _NBD_GetExportInfo_Handler,
		},
		{
			MethodName: "GetDirtyBitmap",
			Handler:    _NBD_GetDirtyBitmap_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Read",
			Handler:       _NBD_Read_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/nbd-com/nbd/v1/nbd.proto",
}

func init() { proto.RegisterFile("pkg/nbd-com/nbd/v1/nbd.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 362 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x41, 0x4f, 0xfa, 0x30,
	0x1c, 0x65, 0x1b, 0xe1, 0x1f, 0x7e, 0xe3, 0x6f, 0x62, 0x0f, 0x3a, 0x88, 0x91, 0xa5, 0x27, 0x2e,
	0x0e, 0x81, 0xb3, 0x1e, 0x26, 0x06, 0x35, 0xca, 0xa1, 0xf1, 0x64, 0xe2, 0xa1, 0x73, 0x05, 0x16,
	0xa4, 0x9d, 0x6b, 0x21, 0xea, 0xe7, 0xf5, 0x83, 0x98, 0x95, 0xe1, 0x36, 0x94, 0x84, 0x53, 0xdb,
	0xf7, 0x7b, 0x7d, 0xeb, 0x7b, 0x6f, 0x70, 0x12, 0xcf, 0xa7, 0x5d, 0x1e, 0x84, 0x67, 0x2f, 0x62,
	0x91, 0xae, 0xdd, 0x55, 0x2f, 0x5d, 0xbc, 0x38, 0x11, 0x4a, 0xa0, 0xc6, 0x7c, 0x19, 0xb0, 0x55,
	0x94, 0x28, 0x8f, 0x07, 0x21, 0x1e, 0xc0, 0xe1, 0xf5, 0x7b, 0x2c, 0x12, 0x75, 0xcb, 0x27, 0x82,
	0xb0, 0xb7, 0x25, 0x93, 0x0a, 0x9d, 0x02, 0x30, 0x0d, 0x8e, 0xe9, 0x82, 0x39, 0x86, 0x6b, 0x74,
	0xea, 0xa4, 0x80, 0xe0, 0x1b, 0x40, 0xc5, 0x4b, 0x32, 0x16, 0x5c, 0x32, 0x84, 0xa0, 0x2a, 0xa3,
	0xcf, 0x35, 0xdf, 0x22, 0x7a, 0x9f, 0x2b, 0xdd, 0x49, 0xc1, 0x1d, 0xd3, 0x35, 0x3a, 0x0d, 0x52,
	0x40, 0xf0, 0x3d, 0xc0, 0x03, 0x8d, 0xf7, 0xfc, 0x6e, 0x3a, 0x0f, 0x22, 0xb5, 0xa0, 0xb1, 0x9e,
	0x9b, 0xeb, 0x79, 0x8e, 0x60, 0x1f, 0x6c, 0xad, 0x96, 0x3d, 0x68, 0x00, 0xff, 0x12, 0x36, 0x8d,
	0x04, 0x97, 0x8e, 0xe1, 0x5a, 0x1d, 0xbb, 0xdf, 0xf4, 0x8a, 0xde, 0xbd, 0x61, 0x94, 0xa8, 0x0f,
	0xa2, 0x19, 0x64, 0xc3, 0xc4, 0x17, 0x60, 0x17, 0x70, 0x74, 0x04, 0x35, 0x31, 0x99, 0x48, 0xa6,
	0x32, 0x5b, 0xd9, 0x29, 0xc5, 0x5f, 0x19, 0x9f, 0xaa, 0x99, 0x7e, 0x86, 0x45, 0xb2, 0x13, 0x7e,
	0x06, 0x9b, 0x30, 0x1a, 0xee, 0xeb, 0x28, 0x97, 0x37, 0x77, 0xc8, 0x5b, 0x25, 0xf9, 0x36, 0xd4,
	0x87, 0x54, 0xd1, 0xab, 0xd9, 0x92, 0xcf, 0xd3, 0xc0, 0x43, 0xaa, 0xa8, 0x96, 0x6d, 0x10, 0xbd,
	0xef, 0x7f, 0x19, 0x60, 0x8d, 0xfd, 0x21, 0x7a, 0x84, 0xff, 0x23, 0xa6, 0xf2, 0x96, 0x50, 0xbb,
	0xec, 0xfd, 0x57, 0xe9, 0x2d, 0x77, 0x37, 0x61, 0x9d, 0x27, 0xae, 0xa0, 0x11, 0x1c, 0x8c, 0x98,
	0xd2, 0xf9, 0xf8, 0x3a, 0x76, 0xe4, 0x94, 0x6f, 0xe5, 0x65, 0xb6, 0x9a, 0x7f, 0x4c, 0x7e, 0x84,
	0x2e, 0xa1, 0x9a, 0xc6, 0x84, 0xb6, 0x48, 0x85, 0xe8, 0x5a, 0xc7, 0x5b, 0x65, 0x6d, 0x6c, 0xe3,
	0xca, 0xb9, 0xe1, 0x57, 0x9f, 0xcc, 0x55, 0x2f, 0xa8, 0xe9, 0x3f, 0x7a, 0xf0, 0x1d, 0x00, 0x00,
	0xff, 0xff, 0xa3, 0xe3, 0x24, 0xea, 0xf1, 0x02, 0x00, 0x00,
}
